name: api-deployment
on:
  push:
    branches:
      - main
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'gringotts-api' }}
  HEROKU_REGISTRY_IMAGE: registry.heroku.com/${APP_NAME}/web
  
steps:
  - uses: actions/checkout@v2
  - name: Heroku Deploy
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    run: |
      heroku container:login
      docker build --tag ${{ env.HEROKU_REGISTRY_IMAGE }}:latest .
      docker push ${{ env.HEROKU_REGISTRY_IMAGE }}:latest
      heroku container:release -a ${{ env.APP_NAME }} web